# Ansible Inventory for DevOps Lab
# This file is auto-generated by Terraform

[jenkins]
${jenkins_public_ip}

[ansible_slave]
${ansible_slave_ip}

[app_server]
${app_server_ip}

[nexus]
${nexus_ip}

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
